### ISSUE TITLE
Support versionPatterns in blocklists

### ISSUE THREAD

**Issue by spyrkob** [wildfly-extras/wildfly-channel#245]
It should be possible to specify the blocked versions as a `versionPattern` similarly to streams in the manifest.

The blocklist should allow to define a list of blocked versions AND a pattern in which case the version would be blocked if it's matched by either.

Optionally - support multiple versionPatterns per block, to simplify more complex cases.

Example blocklist entry:
```
blocks:
  - groupId: "org.test"
     artifactId: "test-one"
     versions:
        - "1.0.0"
        - "1.0.1"
     versionPattern: "2\\..*"
```
