### ISSUE TITLE
Incorrect resolution of the latest manifest from G:A

### ISSUE THREAD

**Issue by TomasHofman** [wildfly-extras/wildfly-channel#265]
When creating a channel instance with GA manifest coordinate, and multiple repositories like:

```
schemaVersion: "2.0.0"
repositories:
  - id: "MRRC"
    url: "https://maven.repository.redhat.com/ga/"
  - id: "brew"
    url: "https://download.devel.redhat.com/brewroot/repos/jb-eap-8.0-maven-build/latest/maven/"
  - id: "indy"
    url: "https://indy.psi.redhat.com/api/content/maven/hosted/pnc-builds/"
manifest:
  maven:
    groupId: "org.jboss.eap.channel"
    artifactId: "eap-8.0"
noStreamStrategy: "none"
```

the manifest may not be resolved to the correct version.

In case when multiple repositories from the list contain the latest manifest artifacts in different versions, like currently MRRC contains manifest version 1.1.1.GA-redhat-00002 and brew already contains 1.2.0.GA-redhat-00009, channel library picks the first resolved version of these two (so essentially the random one), instead of the latest. In effect it may get resolved to 1.1.1.GA-redhat-00002 which is not the latest.

This may be affecting all tooling that resolve channels - prospero, wildfly-channel-maven-plugin, wildfly-maven-plugin, ...

This may be affecting customers using advanced use cases, but probably not majority of customers using the basic use case where only the MRRC repository is used.

Cc @spyrkob @jmesnil
