### ISSUE TITLE
Add schemaName field to Channel

### ISSUE THREAD

**Issue by TomasHofman** [wildfly-extras/wildfly-channel#73]
I'm proposing to add also the "schemaName" field, next to the "schemaVersion" that was added while ago.

It looks that apart from wildfly-channel YAML configuration files, there is also going to be a prospero YAML configuration file which defines other aspects of provisioning configuration. Currently it contains list of channels (specified via GAVs or URLs), and list of Maven repositories. Example of current prospero config:

```yaml
channels:
    gav: "org.jboss.eap.channels:eap-8.0-beta:1.0.0.Beta-redhat-00001"
repositories:
  - "id": "central",
    "url": "https://repo1.maven.org/maven2/"
  - "id": "mrrc",
    "url": "https://maven.repository.redhat.com/ga/"
  - "id": "channel",
    "url": "file:///home/thofman/tmp/m2-repo"
```

It would help to avoid confusing one config file with the other if we specify schema names for each config. The proposal is to have e.g.:

```yaml
schemaName: "wildfly-channel"
schemaVersion: "1.0.0" # already present
name: "Channel for org.jboss.eap:wildfly-ee-galleon-pack:pom:8.0.0.Beta-redhat-20220614\
  \ feature pack."
description: "Generated by org.wildfly.galleon-plugins:wildfly-galleon-maven-plugin\
  \ at 2022-06-14T16:21:17.793742Z"
streams:
  - groupId: "antlr"
    artifactId: "antlr"
    version: "2.7.7.redhat-7"
  - ...
```
and:

```yaml
schemaName: "prospero"
schemaVersion: "1.0.0"
channels:
    gav: "org.jboss.eap.channels:eap-8.0-beta:1.0.0.Beta-redhat-00001"
repositories:
  - "id": "central",
    "url": "https://repo1.maven.org/maven2/"
  - ...
```

**Comment by TomasHofman** [comment]
Cc @jmesnil

**Comment by jmesnil** [comment]
"unexpected attribute" -> is that an error from the wildly-channel.

afaict, if it reads an invalid YAML file, it should report something like "Invalid Channel" (with the underlying schema error).

What would change the addition of a `schemaName` to the YAML file wrt user reporting?

**Comment by TomasHofman** [comment]
So I created a file that reads:

```yaml
schemaVersion: "1.0.0"
repositories:
  - id: test
    url: test
```

and read it with `ChannelMapper.from(file)` and it simply returns empty Channel object, no exception at all. Is that the worst case of all? :)

If nothing else, schemaName would give us a simple way to validate that the file is a channel file. Similarly, prospero would be able to validate the the file given to it is a provisioning config file and not a wildfly channel file.

Sure, we can make wildfly-channel library report "Invalid channel", but reporting something more concrete like "Invalid channel: schemaName is expexted to be 'wildfly-config', not 'prospero'" would I think give me better hint of what I did wrong.

And there is still the human aspect. I have new provisioning tool to use with EAP 8 which I know nothing about. I get two YAML files from support with long filenames that I need to use together. If I open the YAMLs, will I get a hint about what they are?

**Comment by jmesnil** [comment]
```yaml
schemaVersion: "1.0.0"
repositories:
  - id: test
    url: test
```

this file is indeed valid because the Channel schema only requires the `schemaVersion` and will ignore unknown properties such as `repositories`.

> If I open the YAMLs, will I get a hint about what they are?

That's why the Channel spec defines `name` and `description` fields to let a human understand the content of the file.

```yaml
name: "Channel for org.jboss.eap:wildfly-ee-galleon-pack:pom:8.0.0.Beta-redhat-20220614\
  \ feature pack."
```

**Comment by TomasHofman** [comment]
In my opinion the schema validation is very loose. It seems to defeat the purpose of having "schemaVersion" defined. It opens a possibility that an invalid input will pass through the system, producing invalid input (component versions not updated as expected), without anybody noticing.

**Comment by jmesnil** [comment]
> an invalid input will pass through the system, producing invalid input (component versions not updated as expected), without anybody noticing.

could you give an example of such invalid input?

**Comment by TomasHofman** [comment]
* Mistakenly supplying wrong kind of YAML file, as I described above, that happens to have "schemaVersion" attribute.
* Typo:
```yaml
schemaVersion: "1.0.0"
streamsBLAH:
  - groupId: org.jboss.universe
    artifactId: community-universe
    version: 1.2.0.Final
  - ...
```
